- src/main/java/org/joda/time/MonthDay.java
Updated MonthDay.plusDays Javadoc comment to mention that February is
assumed to have 29 days for calculations that require wrapping past the
end of February. Note that the Javadoc for MonthDay in the new Java 8
date API calls out this limitation as well, and explicitly chose not to
support arithmetic on MonthDays for this reason:
http://docs.oracle.com/javase/8/docs/api/java/time/MonthDay.html
> Update MonthDay.plusDays docs

- src/main/java/org/joda/time/ReadableInterval.java
- src/main/java/org/joda/time/base/AbstractInterval.java
Fixes a typo I ran across earlier today.
`mvn clean install` ran successfully.
> Fixes typo. s/exract/extract/

- src/main/java/org/joda/time/Interval.java
- src/main/java/org/joda/time/base/AbstractInterval.java
Fixed bug with overflow in org/joda/time/base/AbstractInterval.toDurationMillis method (if getStartMillis() == Long.MIN_VALUE negating causes uncaught overflow).
Corrected mistake in documentation of org/joda/time/Interval.withEndMillis method.
> Overflow bug fix and documentation fix

- src/main/java/org/joda/time/tz/ZoneInfoCompiler.java
- src/test/java/org/joda/time/tz/TestCompiler.java
The Rule constructor in org.joda.time.tz.ZoneInfoCompiler.java does not
check the number of elements in the StringTokenier obtained from parsing
the timezone file.  There is an assumption that the input TimeZone file
will always be valid, leading to runtime exceptions with no good error
message when the file is invalid. This pull request adds a potential fix
and a test for this issue.
> ZoneInfoCompiler does not check validity of input file

- src/main/java/org/joda/time/tz/ZoneInfoCompiler.java
- src/test/java/org/joda/time/tz/TestCompiler.java
In org.joda.time.tz.ZoneInfoCompiler.java, the number of elements in the StringTokenier obtained from parsing the timezone file is not checked. There is an assumption that the input TimeZone file
will always be valid, leading to runtime exceptions with no good error message when the file is invalid. This pull request adds a potential fix and a test for this issue.
> ZoneInfoCompiler$Zone does not check validity of input file

- src/main/java/org/joda/time/format/DateTimeFormatterBuilder.java
- src/test/java/org/joda/time/format/TestDateTimeFormatterBuilder.java
@jodastephen https://github.com/JodaOrg/joda-time/commit/027bfdde0338f53fc0f20a18a447c52a3f7e02cd introduced a subtle timezone parsing bug into 2.9.x - the binary search implementation doesn't pivot on string length correctly. The material result is that some shorter timezone names won't resolve if there are names in the timezone list that contain the shorter name as a prefix. We encountered this with the timezone `"Etc/GMT"` failing to parse when we upgraded to 2.9.1. This has forced us to rollback to 2.8.2 pending a fix.
> fixes bug in timezone resolution that prevents some timezones being resolved

- src/main/java/org/joda/time/DurationFieldType.java
Simple fix that corrects an apparent typo in comments to DurationFieldType methods
> Fixed comment typo

- README.md
Adding the copy/paste gradle config for the current version -  this prevents users from merely googling 'joda gradle' and helps keep them up to date.
> Adding gradle config + formatting

- src/main/java/org/joda/time/tz/DateTimeZoneBuilder.java
When a DataOutputStream instance is created, it is a good practice to call flush/close explicitly after finish writing to the stream as mentioned for example [here](http://stackoverflow.com/questions/2984538/how-to-use-bytearrayoutputstream-and-dataoutputstream-simultaneously-java). 
Moreover, other places in this project, a close/flush is called on DataOutputStream instance after finish writing to stream for example [here](https://github.com/JodaOrg/joda-time/blob/aaf4396ceb75f39aaa4083f3c96aabc822deeb9e/src/main/java/org/joda/time/tz/ZoneInfoCompiler.java#L453).
In the test [TestBuilder.java](https://github.com/JodaOrg/joda-time/blob/5846d0569dcf64cdfd024f6bf58d707f1a679f64/src/test/java/org/joda/time/tz/TestBuilder.java#L291), a DataOutputStream instance wraps an underlying …
> Fixing DataOutputStream usage

- src/main/java/org/joda/time/tz/ZoneInfoProvider.java
- src/test/java/org/joda/time/TestDateTimeZone.java
Under a security manager, loading resources requries
java.io.FilePermission. This commit modifies the loading of such
resources so they are done in an appropriate doPrivileged block.
Closes #327
> Load timezone resources in doPrivileged block

- pom.xml
Fixes #284 by generating an additional sources JAR and adding the existing Javadoc JAR again.  I couldn't see how to generate Javadoc again with different exclusions without a lot of duplicated config, but that is probably not necessary for most tooling, and doesn't seem to be needed by Android Studio to fix the attached defect.
Probably an FYI rather than a fix that is worth implementing, though you could always upload the additional JARs to Maven central even if a new version is not required.
> fixes #284 - Generate source and Javadoc artifacts for no-tzdb artifact

- RELEASE-NOTES.txt
- pom.xml
- src/main/java/org/joda/time/tz/src/africa
- src/main/java/org/joda/time/tz/src/antarctica
- src/main/java/org/joda/time/tz/src/asia
- src/main/java/org/joda/time/tz/src/australasia
- src/main/java/org/joda/time/tz/src/backward
- src/main/java/org/joda/time/tz/src/etcetera
- src/main/java/org/joda/time/tz/src/europe
- src/main/java/org/joda/time/tz/src/northamerica
- src/main/java/org/joda/time/tz/src/southamerica
Turkey recently switched to DST permanently, i.e. is going to remain on UTC+3 all year round. Latest version of the database addresses this.
> Update TimeZone Database to 2016g

- src/main/java/org/joda/time/base/AbstractInterval.java
2.8.3 updated this message to more accurately reflect the check being done (which was great), but the update made the error message less human-friendly and grammatically incorrect.
> Cleaner AbstractInterval.checkInterval error msg

- src/main/java/org/joda/time/DateTimeZone.java
- src/main/java/org/joda/time/tz/ZoneInfoProvider.java
As there is no ZoneInfoProvider() constructor, it is not possible to
specify org.joda.time.tz.ZoneInfoProvider with the system property
org.joda.time.DateTimeZone.Provider; this patch addresses this.
The Joda-Time project has been running for many years now, and the codebase is stable.
Java SE 8 contains a new date and time library that is the successor to Joda-Time.
As such Joda-Time is primarily in maintainence mode and few pull requests are likely to be merged.
> Add ZoneInfoProvider() constructor

- src/site/xdoc/cal_ethiopic.xml
Looks like the title of this page wasn't updated when copying the documentation template from Coptic calendar docs.
> Fix title of Ethiopic calendar doc page

- src/main/java/org/joda/time/Instant.java
- src/test/java/org/joda/time/TestInstant_Constructors.java
Add `Instant.ofEpochMilli(long epochMilli)` and `Instant.ofEpochSecond(long epochSecond)`
Fixes https://github.com/JodaOrg/joda-time/issues/445
> Add `Instant.ofEpochMilli(long epochMilli)` and `Instant.ofEpochSecond(long epochSecond)`

- README.md
The project home page and pull request template indicate that the library is no longer under active development but the README currently shows no indication of this which could lead to wasted effort (e.g. #479). 
The README should certainly not state that calendaring system additions are welcome!
> Indicate the library is not actively developed

- src/main/java/org/joda/time/Period.java
Fixed a possible type in Period constructor. This doesn't seem to have any negative impact for now.
* Removed 9th element in Period init array
> Fixed Typo in Period Constructor

- src/main/java/org/joda/time/Chronology.java
The Joda-Time project has been running for many years now, and the codebase is stable.
Java SE 8 contains a new date and time library that is the successor to Joda-Time.
As such Joda-Time is primarily in maintainence mode and few pull requests are likely to be merged.
**As a general rule, most enhancement PRs will now be rejected.**
To save wasted effort, it is recommended that an issue is raised first.
The issue should clearly indicate that a PR is intended, and request approval for the work.
If you still want to raise a PR, please delete this text!
> Remove extra whitespace in weekyearOfCentury declaration

- README.md
@jodastephen this PR adds the following copy to the README between "related projects" and "support"
For enterprise
Available as part of the Tidelift Subscription.
Joda and the maintainers of thousands of other packages are working with Tidelift to deliver one enterprise subscription that covers all of the open source you use.
If you want the flexibility of open source and the confidence of commercial-grade software, this is for you.
Learn more
> Adding for enterprise section

- src/changes/changes.xml
Release date for 2.10.10 on https://www.joda.org/joda-time/changes-report.html shows 2020-02-05 instead of 2021-02-05.
> Fix release date for 2.10.10

- src/main/java/org/joda/time/tz/ZoneInfoCompiler.java
`count` is a `short`, so it should be compared against `Short.MAX_VALUE`, not `Integer.MAX_VALUE`.
The Joda-Time project has been running for many years now, and the codebase is stable.
Java SE 8 contains a new date and time library that is the successor to Joda-Time.
As such Joda-Time is primarily in maintenance mode and few pull requests are likely to be merged.
**As a general rule, most enhancement PRs will now be rejected.**
To save wasted effort, it is recommended that an issue is raised first.
The issue should clearly indicate that a PR is intended, and request approval for the work.
If you still want to raise a PR, please delete this text!
> Fix bug in ZoneInfoCompiler.writeZoneInfoMap()

- src/main/java/org/joda/time/format/DateTimeFormat.java
Hello, 
The proposed change is a very minor improvement to the exception message in DateTimeFormatter when the input is null or empty.
Current exception text: 
```
Invalid pattern specification
```
Proposed exception text:
```
Invalid pattern specification. Pattern is null or empty.
```
Rationale: 
An IllegalArgumentException is thrown if the pattern does not respect the ISO-8601 format OR if the pattern is null or empty.
The current exception text for null or empty case does not make it clear that the issue is not a ISO-8601 format issue but a null/empty issue. 
I lost some time on this when debugging. I think the proposed change can only improve the joda user experience, and does not add complexity to the codebase.
I did not open an issue, sorry about this, it was simpler to show the …
> improve exception message in DateTimeFormatter

- src/main/java/org/joda/time/convert/ConverterManager.java
- src/test/java/org/joda/time/convert/TestConverterManager.java
We encountered a TSAN error because 2 threads were racing to call
`ConverterManager.getInstance()`. My read is that the current code could
actually be unsafe, since one thread might see `INSTANCE` as non-null
before the other thread has initialized its fields.
Fortunately, this looks like a good case for [the
initialization-on-demand holder
idiom](https://www.cs.umd.edu/~pugh/java/memoryModel/jsr-133-faq.html#:~:text=initialization%20on%20demand%20holder%20idiom).
(There would be additional thread-safety concerns if anyone were to try
to _mutate_ the `ConverterManager` instance concurrently with usage. But
I'm not sure there's a solution to that short of spraying `synchronized`
around. That seems like probably overkill, given the possible
performance impact for what I'd hope is an …
> Make `ConverterManager.getInstance()` init thread-safe.
